
INSERT INTO Docente (Nombre, ApPaterno, ApMaterno, Email) VALUES
('Roberto', 'Barrón', 'Ríos', 'roberto.barron@leon.tecnm.mx'),
('Cruz Yuliana', 'Calderón', 'Hermosillo', 'yuliana.calderon@leon.tecnm.mx'),
('María del Carmen Virginia', 'Cervantes', 'Salgado', 'madelcarmen.cervantes@leon.tecnm.mx'),
('Ramón', 'Díaz', 'Hernández', 'ramon.diaz@leon.tecnm.mx'),
('Luis', 'García', 'Márquez', 'luis.garcia@leon.tecnm.mx'),
('José Alfredo', 'Gasca', 'González', 'josealfredo.gasca@leon.tecnm.mx'),
('Héctor Federico', 'Godínez', 'Cabrera', 'hectorfederico.godinez@leon.tecnm.mx'),
('Francisco Alfredo', 'Granados', 'Ramírez', 'franciscoalfredo.granados@leon.tecnm.mx'),
('Brenda Rosario', 'Hernández', 'Palafox', 'brendarosario.hernandez@leon.tecnm.mx'),
('José Fernando', 'Hernández', 'Rodríguez', 'jose.hernandez@leon.tecnm.mx'),
('Ivett Adriana', 'Hidalgo', 'Montenegro', 'ivett.hidalgo@leon.tecnm.mx'),
('Myriam Aidee', 'Huizar', 'Kolldell', 'aidee.huizar@leon.tecnm.mx'),
('Rogelio', 'Infante', 'Medina', 'rogelio.infante@leon.tecnm.mx'),
('Flor Karina', 'Juárez', 'Cárdenas', 'flor.juarez@leon.tecnm.mx'),
('Antonio', 'Lona', 'Gámez', 'antonio.lona@leon.tecnm.mx'),
('J. Félix', 'López', 'Rocha', 'felix.lopez@leon.tecnm.mx'),
('Denisse', 'Medina', 'López', 'denisse.medina@leon.tecnm.mx'),
('Omar Felipe', 'Ortega', 'Martínez', 'omarfelipe.ortega@leon.tecnm.mx'),
('Luis Carlos', 'Padierna', 'García', 'luiscarlos.padierna@leon.tecnm.mx'),
('Juan de Dios', 'Paz', 'Salinas', 'juandedios.paz@leon.tecnm.mx'),
('Luz María Trinidad', 'Pérez', 'Alvarado', 'luzmaria.perez@leon.tecnm.mx'),
('Graciano', 'Ramírez', 'Bravo', 'graciano.ramirez@leon.tecnm.mx'),
('Joel', 'Rico', 'Pérez', 'joel.rico@leon.tecnm.mx'),
('Eduardo', 'Rodríguez', 'Argüello', 'eduardo.rodriguez@leon.tecnm.mx'),
('Mónica De Los Dolores', 'Rodríguez', 'Chávez', 'monica.rodriguez@leon.tecnm.mx'),
('Rodolfo', 'Rodríguez', 'Padilla', 'rodolfo.rodriguez@leon.tecnm.mx'),
('Saúl', 'Ruiz', 'Berbena', 'saul.ruiz@leon.tecnm.mx'),
('Manuel', 'Sambrano', 'Sánchez', 'manuel.sambrano@leon.tecnm.mx'),
('José Ramón', 'Tapia', 'Torres', 'ramon.tapia@leon.tecnm.mx'),
('Rubén', 'Trujillo', 'Corona', 'ruben.trujillo@leon.tecnm.mx'),
('Iván', 'Vigueras', 'Montaño', 'ivan.vigueras@leon.tecnm.mx'),
('Leonel Alejandro', 'Villanueva', 'Ríos', 'leonel.villanueva@leon.tecnm.mx'),
('José Luis', 'Villanueva', 'Rodríguez', 'joseluis.villanueva@leon.tecnm.mx'),
('Rafael', 'Rodríguez', 'Gallegos', 'rafael.rodriguez@leon.tecnm.mx');