INSERT INTO Docente (Nombre, ApPaterno, ApMaterno, GradoEstudio, Email, Foto) VALUES
('Roberto', 'Barrón', 'Ríos', 'Licenciatura', 'roberto.barron@leon.tecnm.mx', 'NONE'),
('Cruz Yuliana', 'Calderón', 'Hermosillo', 'Licenciatura', 'yuliana.calderon@leon.tecnm.mx', 'NONE'),
('María del Carmen Virginia', 'Cervantes', 'Salgado', 'Licenciatura', 'madelcarmen.cervantes@leon.tecnm.mx', 'NONE'),
('Ramón', 'Díaz', 'Hernández', 'Licenciatura', 'ramon.diaz@leon.tecnm.mx', 'NONE'),
('Luis', 'García', 'Márquez', 'Licenciatura', 'luis.garcia@leon.tecnm.mx', 'NONE'),
('José Alfredo', 'Gasca', 'González', 'Licenciatura', 'josealfredo.gasca@leon.tecnm.mx', 'NONE'),
('Héctor Federico', 'Godínez', 'Cabrera', 'Licenciatura', 'hectorfederico.godinez@leon.tecnm.mx', 'NONE'),
('Francisco Alfredo', 'Granados', 'Ramírez', 'Licenciatura', 'franciscoalfredo.granados@leon.tecnm.mx', 'NONE'),
('Brenda Rosario', 'Hernández', 'Palafox', 'Licenciatura', 'brendarosario.hernandez@leon.tecnm.mx', 'NONE'),
('José Fernando', 'Hernández', 'Rodríguez', 'Licenciatura', 'jose.hernandez@leon.tecnm.mx', 'NONE'),
('Ivett Adriana', 'Hidalgo', 'Montenegro', 'Licenciatura', 'ivett.hidalgo@leon.tecnm.mx', 'NONE'),
('Myriam Aidee', 'Huizar', 'Kolldell', 'Licenciatura', 'aidee.huizar@leon.tecnm.mx', 'NONE'),
('Rogelio', 'Infante', 'Medina', 'Licenciatura', 'rogelio.infante@leon.tecnm.mx', 'NONE'),
('Flor Karina', 'Juárez', 'Cárdenas', 'Licenciatura', 'flor.juarez@leon.tecnm.mx', 'NONE'),
('Antonio', 'Lona', 'Gámez', 'Licenciatura', 'antonio.lona@leon.tecnm.mx', 'NONE'),
('J. Félix', 'López', 'Rocha', 'Licenciatura', 'felix.lopez@leon.tecnm.mx', 'NONE'),
('Denisse', 'Medina', 'López', 'Licenciatura', 'denisse.medina@leon.tecnm.mx', 'NONE'),
('Omar Felipe', 'Ortega', 'Martínez', 'Licenciatura', 'omarfelipe.ortega@leon.tecnm.mx', 'NONE'),
('Luis Carlos', 'Padierna', 'García', 'Licenciatura', 'luiscarlos.padierna@leon.tecnm.mx', 'NONE'),
('Juan de Dios', 'Paz', 'Salinas', 'Licenciatura', 'juandedios.paz@leon.tecnm.mx', 'NONE'),
('Luz María Trinidad', 'Pérez', 'Alvarado', 'Licenciatura', 'luzmaria.perez@leon.tecnm.mx', 'NONE'),
('Graciano', 'Ramírez', 'Bravo', 'Licenciatura', 'graciano.ramirez@leon.tecnm.mx', 'NONE'),
('Joel', 'Rico', 'Pérez', 'Licenciatura', 'joel.rico@leon.tecnm.mx', 'NONE'),
('Eduardo', 'Rodríguez', 'Argüello', 'Licenciatura', 'eduardo.rodriguez@leon.tecnm.mx', 'NONE'),
('Mónica De Los Dolores', 'Rodríguez', 'Chávez', 'Licenciatura', 'monica.rodriguez@leon.tecnm.mx', 'NONE'),
('Rodolfo', 'Rodríguez', 'Padilla', 'Licenciatura', 'rodolfo.rodriguez@leon.tecnm.mx', 'NONE'),
('Saúl', 'Ruiz', 'Berbena', 'Licenciatura', 'saul.ruiz@leon.tecnm.mx', 'NONE'),
('Manuel', 'Sambrano', 'Sánchez', 'Licenciatura', 'manuel.sambrano@leon.tecnm.mx', 'NONE'),
('José Ramón', 'Tapia', 'Torres', 'Licenciatura', 'ramon.tapia@leon.tecnm.mx', 'NONE'),
('Rubén', 'Trujillo', 'Corona', 'Licenciatura', 'ruben.trujillo@leon.tecnm.mx', 'NONE'),
('Iván', 'Vigueras', 'Montaño', 'Licenciatura', 'ivan.vigueras@leon.tecnm.mx', 'NONE'),
('Leonel Alejandro', 'Villanueva', 'Ríos', 'Licenciatura', 'leonel.villanueva@leon.tecnm.mx', 'NONE'),
('José Luis', 'Villanueva', 'Rodríguez', 'Licenciatura', 'joseluis.villanueva@leon.tecnm.mx', 'NONE'),
('Rafael', 'Rodríguez', 'Gallegos', 'Licenciatura', 'rafael.rodriguez@leon.tecnm.mx', 'NONE'),
('Analía', 'Zamudio', 'Carrera', 'Licenciatura', 'analiazam@leon.tecnm.mx', 'NONE'),
('Annel Asminy', 'Ramos', 'Gándara', 'Licenciatura', 'annel.ramos@leon.tecnm.mx', 'NONE'),
('César Agustín', 'Arroyo', 'Rico', 'Licenciatura', 'cesar.arroyo@leon.tecnm.mx', 'NONE'),
('Humberto', 'León', 'López', 'Licenciatura', 'humberto.leon@leon.tecnm.mx', 'NONE'),
('Ma. Isabel Cristina', 'Cárdenas', 'Salazar', 'Licenciatura', 'isabel.cardenas@leon.tecnm.mx', 'NONE'),
('Ismael', 'Bustos', 'Razo', 'Licenciatura', 'ismael.bustos@leon.tecnm.mx', 'NONE'),
('Jorge', 'Alfaro', NULL, 'Licenciatura', 'jorge.gomez@leon.tecnm.mx', 'NONE'),
('José Antonio', 'Donato', 'Montiel', 'Licenciatura', 'joseantonio.donato@leon.tecnm.mx', 'NONE'),
('Julio César', 'González', 'Sánchez', 'Licenciatura', 'julio.gonzalez@leon.tecnm.mx', 'NONE'),
('Mariana Guadalupe', 'García', 'Vargas', 'Licenciatura', 'marianaguadalupe.garcia@leon.tecnm.mx', 'NONE'),
('Mario', 'Rocha', 'Hernández', 'Licenciatura', 'mario.hernandez@leon.tecnm.mx', 'NONE'),
('Adriana Edurne', 'Macías', 'García', 'Licenciatura', 'adriana.macias@leon.tecnm.mx', 'NONE'),
('Ma. de los Ángeles', 'Gómez', 'Castro', 'Licenciatura', 'angeles.gomez@leon.tecnm.mx', 'NONE'),
('Martha Beatriz', 'López', 'Mena', 'Licenciatura', 'martha.lopez@leon.tecnm.mx', 'NONE'),
('Carla Patricia', 'Ordaz', 'Picón', 'Licenciatura', 'carla.ordaz@leon.tecnm.mx', 'NONE'),
('Celia', 'Ibarra', 'Díaz', 'Licenciatura', 'celia.ibarra@leon.tecnm.mx', 'NONE'),
('Claudia Araceli', 'Caudillo', 'Peñaflor', 'Licenciatura', 'claudiacaudillo@leon.tecnm.mx', 'NONE'),
('Claudia Leticia', 'Díaz', 'González', 'Licenciatura', 'claudia.diaz@leon.tecnm.mx', 'NONE'),
('Daniel Arturo', 'Olivares', 'Vera', 'Licenciatura', 'danielarturo.olivares@leon.tecnm.mx', 'NONE'),
('Ma. Eugenia', 'Pérez', 'Parra', 'Licenciatura', 'eugenia.parra@leon.tecnm.mx', 'NONE'),
('Fabiola Hilda Esther', 'Mares', 'Rodríguez', 'Licenciatura', 'fabiola.mares@leon.tecnm.mx', 'NONE'),
('Fabiola', 'Nolasco', 'Rivera', 'Licenciatura', 'fabiola.nolasco@leon.tecnm.mx', 'NONE'),
('Francisco Javier', 'Ruíz', 'González', 'Licenciatura', 'franciscojavier.ruiz@leon.tecnm.mx', 'NONE'),
('Gerardo', 'Ramírez', 'Gómez', 'Licenciatura', 'gerardo.ramirez@leon.tecnm.mx', 'NONE'),
('Héctor Eduardo', 'Rosales', 'Moreno', 'Licenciatura', 'hector.rosales@leon.tecnm.mx', 'NONE'),
('Jesús Roberto', 'Fernández', 'Ramírez', 'Licenciatura', 'jesusroberto.fernandez@leon.tecnm.mx', 'NONE'),
('Laura Alicia', 'Pérez', 'García', 'Licenciatura', 'laura.perez@leon.tecnm.mx', 'NONE'),
('Leticia', 'Aguirre', 'Ledesma', 'Licenciatura', 'leticia.aguirre@leon.tecnm.mx', 'NONE'),
('Luis Arturo', 'González', 'Martínez', 'Licenciatura', 'luisarturo.gonzalez@leon.tecnm.mx', 'NONE'),
('Luis Felipe', 'Juárez', 'Ramírez', 'Licenciatura', 'luisfelipe.juarez@leon.tecnm.mx', 'NONE'),
('Luis Enrique', 'León', 'Rosas', 'Licenciatura', 'luisenrique.leon@leon.tecnm.mx', 'NONE'),
('Luis Manuel', 'Varela', 'Pérez', 'Licenciatura', 'luismanuel.varela@leon.tecnm.mx', 'NONE'),
('María Alejandra', 'Mendoza', 'Mena', 'Licenciatura', 'maria.mendoza@leon.tecnm.mx', 'NONE'),
('María de la Luz', 'Trevizo', 'Jaramillo', 'Licenciatura', 'maria.trevizo@leon.tecnm.mx', 'NONE'),
('María del Socorro', 'Mejía', 'Ruelas', 'Licenciatura', 'maria.mejia@leon.tecnm.mx', 'NONE'),
('Martín', 'Ramírez', 'Márquez', 'Licenciatura', 'martin.ramirez@leon.tecnm.mx', 'NONE'),
('Mauricio', 'Jiménez', 'Rodríguez', 'Licenciatura', 'mauricio.jimenez@leon.tecnm.mx', 'NONE'),
('Pablo', 'Pichardo', 'Gómez', 'Licenciatura', 'pablo.pichardo@leon.tecnm.mx', 'NONE'),
('Patricia Eugenia', 'Jiménez', 'Jaime', 'Licenciatura', 'patricia.jimenez@leon.tecnm.mx', 'NONE'),
('Sergio Fernando', 'Lozano', 'Guerrero', 'Licenciatura', 'sergio.lozano@leon.tecnm.mx', 'NONE'),
('Verónica', 'Hernández', 'Castañeda', 'Licenciatura', 'veronica.hernandez@leon.tecnm.mx', 'NONE'),
('Yatzari Carolina', 'García', 'Romo', 'Licenciatura', 'yatzari.garcia@leon.tecnm.mx', 'NONE'),
('José Alfredo', 'Cruz', 'Bernal', 'Licenciatura', 'josealfredo.cruz@leon.tecnm.mx', 'NONE'),
('José Esteban', 'Gómez', 'Ledesma', 'Licenciatura', 'joseesteban.gomez@leon.tecnm.mx', 'NONE'),
('Luz del Carmen', 'Aguayo', 'Vega', 'Licenciatura', 'luzcarmen.aguayo@leon.tecnm.mx', 'NONE'),
('David', 'Rodríguez', 'Esquivel', 'Licenciatura', 'david.rodriguez@leon.tecnm.mx', 'NONE');
