INSERT INTO Docente (Nombre, Apellido_Paterno, Apellido_Materno, Grado_Academico, Correo, Observaciones) VALUES
('José Fernando', 'Aguiñaga', 'Rodríguez', 'Licenciatura', 'josefernando.aguinaga@leon.tecnm.mx', 'NONE'),
('Jesús Eduardo', 'Aldape', '', 'Licenciatura', 'eduardo.aldape@leon.tecnm.mx', 'NONE'),
('Yaret Viridiana', 'Alonso', 'Rangel', 'Licenciatura', 'yaretviridiana.alonso@leon.tecnm.mx', 'NONE'),
('José Luis', 'Araiza', 'Guzmán', 'Licenciatura', 'joseluis.araiza@leon.tecnm.mx', 'NONE'),
('Oscar Armando', 'Calcanas', 'Lerma', 'Licenciatura', 'oscar.calcanas@leon.tecnm.mx', 'NONE'),
('María Lorena', 'Cázares', 'Coss Y León', 'Licenciatura', 'maria.cazares@leon.tecnm.mx', 'NONE'),
('Primitivo', 'Del Ángel', 'Soto', 'Licenciatura', 'primitivo.delangel@leon.tecnm.mx', 'NONE'),
('Israel', 'Esteban', 'López', 'Licenciatura', 'israel.esteban@leon.tecnm.mx', 'NONE'),
('Ángel Ignacio', 'Estrada', 'Lujano', 'Licenciatura', 'angelignacio.estrada@leon.tecnm.mx', 'NONE'),
('Eduardo', 'Estrada', 'Palomino', 'Licenciatura', 'eduardo.estrada@leon.tecnm.mx', 'NONE'),
('Noé Cesar', 'Estrada', 'Quiroz', 'Licenciatura', 'noecesar.estrada@leon.tecnm.mx', 'NONE'),
('Karla Angélica', 'García', 'Barrón', 'Licenciatura', 'karlaangelica.garcia@leon.tecnm.mx', 'NONE'),
('Abigail', 'García', 'Rangel', 'Licenciatura', 'abigail.garcia@leon.tecnm.mx', 'NONE'),
('Guillermo', 'García', 'Rodríguez', 'Licenciatura', 'guillermo.garcia@leon.tecnm.mx', 'NONE'),
('María Elena', 'García', 'Sotelo', 'Licenciatura', 'mariaelena.garcia@leon.tecnm.mx', 'NONE'),
('Gustavo Adolfo', 'Garnica', 'Arista', 'Licenciatura', 'gustavoadolfo.garnica@leon.tecnm.mx', 'NONE'),
('Irma Yareni', 'Gómez', 'Fuentes', 'Licenciatura', 'irma.gomez@leon.tecnm.mx', 'NONE'),
('Fernando', 'Gómez', 'Guerra', 'Licenciatura', 'fernando.gomez@leon.tecnm.mx', 'NONE'),
('Mónica', 'Gutiérrez', 'Del Real', 'Licenciatura', 'monica.gutierrez@leon.tecnm.mx', 'NONE'),
('Guillermina', 'Hernández', 'Hernández', 'Licenciatura', 'guillermina.hernandez@leon.tecnm.mx', 'NONE'),
('María Raquel', 'Hernández', 'Segura', 'Licenciatura', 'raquel.hernandez@leon.tecnm.mx', 'NONE'),
('José', 'Hurtado', 'Martínez', 'Licenciatura', 'jose.hurtado@leon.tecnm.mx', 'NONE'),
('Martha Patricia', 'Hurtado', 'Martínez', 'Licenciatura', 'marthapatricia.hurtado@leon.tecnm.mx', 'NONE'),
('Juan Manuel', 'Luna', 'Valle', 'Licenciatura', 'manuel.luna@leon.tecnm.mx', 'NONE'),
('Juan Manuel Edmundo', 'Martínez', 'Camacho', 'Licenciatura', 'juanmanuel.martinez@leon.tecnm.mx', 'NONE'),
('Juan Manuel', 'Meza', 'Muñoz', 'Licenciatura', 'juanmanuel.meza@leon.tecnm.mx', 'NONE'),
('Francisco', 'Meza', 'Navarro', 'Licenciatura', 'francisco.meza@leon.tecnm.mx', 'NONE'),
('Adolfo', 'Montesinos', '', 'Licenciatura', 'm08240762@leon.tecnm.mx', 'NONE'),
('Víctor Ulises', 'Muñoz', 'Brizuela', 'Licenciatura', 'victor.munoz@leon.tecnm.mx', 'NONE'),
('Hugo Alberto', 'Muñoz', 'Rodríguez', 'Licenciatura', 'hugo_mrodriguez@leon.tecnm.mx', 'NONE'),
('Felipe', 'Ortega', 'Moreno', 'Licenciatura', 'felipe.ortega@leon.tecnm.mx', 'NONE'),
('Pablo Gregorio', 'Pérez', 'Campos', 'Licenciatura', 'pablogregorio.perez@leon.tecnm.mx', 'NONE'),
('Juan Antonio', 'Pérez', 'López', 'Licenciatura', 'juanantonio.perez@leon.tecnm.mx', 'NONE'),
('Cesar Mauricio', 'Reyes', 'Mendoza', 'Licenciatura', 'cesarmauricio.reyes@leon.tecnm.mx', 'NONE'),
('Roberto', 'Robledo', 'Pérez', 'Licenciatura', 'roberto.robledo@leon.tecnm.mx', 'NONE'),
('Ana Cecilia', 'Ruiz', 'Segoviano', 'Licenciatura', 'liliaberenice.rodriguez@leon.tecnm.mx', 'NONE'),
('Mónica', 'Salgado', 'Solís', 'Licenciatura', 'monica.salgado@leon.tecnm.mx', 'NONE'),
('Francisco Héctor', 'Santos', 'Ruiz', 'Licenciatura', 'santos@leon.tecnm.mx', 'NONE'),
('Margarita', 'Sarabia', 'Saldaña', 'Licenciatura', 'margarita.sarabia@leon.tecnm.mx', 'NONE'),
('José Luis', 'Servín', 'Lara', 'Licenciatura', 'joseluis.servin@leon.tecnm.mx', 'NONE'),
('Leopoldo David', 'Tapia', 'Torres', 'Licenciatura', 'leopoldo.tapia@leon.tecnm.mx', 'NONE'),
('Lilia Angélica', 'Vázquez', 'Gutiérrez', 'Licenciatura', 'lilia.vazquez@leon.tecnm.mx', 'NONE');
