INSERT INTO Docente (Nombre, ApPaterno, ApMaterno, Email) VALUES
('Bulmaro', 'Aranda', 'Cervantes', 'bulmaro.aranda@leon.tecnm.mx'),
('Juan Carlos', 'Ayala', 'Martínez', 'juancarlos.ayala@leon.tecnm.mx'),
('José Antonio', 'Calderón', 'Guzmán', 'joseantonio.calderon@leon.tecnm.mx'),
('Miguel Ángel', 'Casillas', 'Araiza', 'miguel.casillas@leon.tecnm.mx'),
('Josué', 'DelValle', 'Hernández', 'josue.delvalle@leon.tecnm.mx'),
('Luis Miguel', 'González', 'Ortiz', 'luismiguel.gonzalez@leon.tecnm.mx'),
('Araceli', 'Guerrero', 'Cabrera', 'araceli.guerrero@leon.tecnm.mx'),
('Jesús', 'Hernández', 'Ibarra', 'jesus.hernandez@leon.tecnm.mx'),
('Gerardo De Jesús', 'Loza', 'Angulo', 'gerardodejesus.loza@leon.tecnm.mx'),
('Antonio', 'Martínez', 'Báez', 'jose.martinez@leon.tecnm.mx'),
('José De Jesús', 'Mayagoitia', 'Barragán', 'josedejesus.mayagoitia@leon.tecnm.mx'),
('Rogelio', 'Navarro', 'Rizo', 'rogelio.navarro@leon.tecnm.mx'),
('Adrián', 'Pérez', 'Benavidez', 'adrian.perez@leon.tecnm.mx'),
('Francisco Alejandro', 'Ramírez', 'Díaz', 'francisco.ramirez@leon.tecnm.mx'),
('Juan José', 'Ramírez', 'Zermeño', 'juan.ramirez@leon.tecnm.mx'),
('Luis Omar', 'Rojas', 'Juárez', 'omar.rojas@leon.tecnm.mx'),
('Miguel', 'Rosales', 'Ciceña', 'mrosales@leon.tecnm.mx'),
('José Luis', 'Torres', 'Gutiérrez', 'joseluis.torres@leon.tecnm.mx'),
('Rubén Eugenio', 'Valdivia', 'Hernández', 'ruben.valdivia@leon.tecnm.mx'),
('Juan Mauricio', 'Valtierra', 'Domínguez', 'mauricio.valtierra@leon.tecnm.mx'),
('Ricardo', 'Vázquez', 'González', 'ricardo.vazquez@leon.tecnm.mx'),
('José Luis', 'Villaseñor', 'Ortega', 'jose.villasenor@leon.tecnm.mx'),
('Antonio', 'Zamarrón', 'Ramírez', 'zamarron@leon.tecnm.mx'),
('Gerardo', 'Gutiérrez', 'Torres', 'gerardo.gutierrez@leon.tecnm.mx'),
('Francisco', 'Chávez', 'Gutiérrez', 'francisco.chavez@leon.tecnm.mx'),
('Sorangel', 'Fischer', 'Hernández', 'sarangelfischerhernandez@leon.tecnm.mx'),
('Enrique', 'Hernández', 'Parra', 'enriquehernandezparra@leon.tecnm.mx'),
('Sandra Jaqueline', 'López', 'Cervera', 'sandrajaqueline.lopez@leon.tecnm.mx'),
('Alan', 'López', 'Martínez', 'alan.lopez@leon.tecnm.mx'),
('Francisco Carlos', 'Mejía', 'Alanís', 'franciscocarlos.mejia@leon.tecnm.mx'),
('Guillermo Eduardo', 'Méndez', 'Zamora', 'guillermoeduardo.mendez@leon.tecnm.mx'),
('Dante José', 'Migoni', 'León', 'dantejose.migoni@leon.tecnm.mx'),
('Jorge Daniel', 'Moreno', 'Gómez', 'jorgedaniel.moreno@leon.tecnm.mx'),
('Hul', 'Padilla', 'Gómez', 'hul.padilla@leon.tecnm.mx'),
('Leonardo', 'Pérez', 'Mayen', 'leonardo.perez@leon.tecnm.mx'),
('Marco Antonio', 'Pérez', 'Tovar', 'marcoantonio.perez@leon.tecnm.mx'),
('Hugo Marcel', 'Saavedra', 'Hernández', 'hugomarcel.saavedra@leon.tecnm.mx'),
('Omar', 'Sistos', 'Iñiguez', 'omar.sistos@leon.tecnm.mx'),
('Osccar Salvador', 'Torres', 'Muñoz', 'osccar.torres@leon.tecnm.mx'),
('Alejandro', 'Torres', 'Pérez', 'alejandro.torres@leon.tecnm.mx'),
('Carlos', 'Zamarripa', 'Ramírez', 'carlos.zamarripa@leon.tecnm.mx'),
('Esteban', 'Orozco', '', 'esteban.orozco@leon.tecnm.mx'),
('Leonardo', 'Meza', 'Muñoz', 'lmeza@leon.tecnm.mx');