INSERT INTO Docente (Nombre, ApPaterno, ApMaterno, Email, GradoEstudio, Foto) VALUES
('Gerardo David', 'Aguayo', 'Ríos', 'daguayo@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Antonio', 'Águila', 'Reyes', 'antonio.aguila@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Juan Carlos', 'Aguilera', 'Cruz', 'juancarlos.aguilera@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Efraín Guadalupe', 'Bermúdez', '', 'efrain.bermudez@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('José De Jesús', 'Cardona', 'Delgado', 'josedejesus.cardona@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('José Gerardo', 'Carpio', 'Flores', 'carpiofloresjosegerardo@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Elizabeth', 'Castellanos', 'Nolasco', 'ecastell@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Patricia María', 'Castillo', 'Martínez', 'patriciamaria.castillo@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Elsa', 'Cuevas', 'Carrillo', 'elsa.cc@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('María Alicia', 'Ríos', 'Constantino', 'alicia.rios@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Martha Alicia', 'Rocha', 'Sánchez', 'marthaalicia.rocha@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('José Alejandro', 'Rodríguez', 'Rentería', 'josealejandro.rodriguez@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Luz Del Carmen', 'Ruiz', 'Gaytán', 'luzdelcarmen.ruiz@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Ruth', 'Sáez', 'De Nanclares', 'ruth.saezdenanclares@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('José De Jesús', 'Sandoval', 'Palomares', 'jose.sandoval@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('María Concepción', 'Sandoval', 'Solís', 'maconcepcion.sandoval@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('María Minerva', 'Saucedo', 'Torres', 'minerva.saucedo@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Cirino', 'Silva', 'Tovar', 'cirino.silva@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('José Luis Fernando', 'Suarez', 'Y Gómez', 'suarez@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Verónica', 'Tapia', 'Ibarra', 'veronica.tapia@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Carlos Alberto', 'Trujillo', 'Castellanos', 'carlosalberto.trujillo@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('María Magdalena', 'Valdivia', 'Murillo', 'magdalena.valdivia@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('José Juan', 'Vallejo', 'Núñez', 'jvallejo@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Miguel Ángel', 'Vázquez', 'Rivas', 'angel.rivas@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Miguel Ángel', 'Peña', 'López', 'mangel.plopez@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Juan Pablo', 'Cordero', 'Hernández', 'jpcordero@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Edgar Manuel', 'Delgado', 'Tolentino', 'edgar.delgado@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Luis Roberto', 'Gallegos', 'Muñoz', 'luisroberto.gallegos@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Paola Virginia', 'Galván', 'Jaramillo', 'paola.galvan@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Adolfo', 'Gamiño', 'Guerrero', 'adolfo.gamino@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Domingo', 'García', 'Ornelas', 'domingo.garcia@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Alejandro', 'García', 'Trujillo', 'alejandro.garcia@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Laura Patricia', 'Guevara', 'Rangel', 'laurapatricia.guevara@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Luis Eduardo', 'Gutiérrez', 'Ayala', 'lgtez@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Laura', 'Juárez', 'Guerra', 'laura.juarez@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Luis Gabino', 'Landeros', 'Aranda', 'luisgla@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Carlos Rafael', 'Levy', 'Rojas', 'crlevys@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('David Everardo', 'Lugo', 'Pedroza', 'david.lugo@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Eugenio Conrado', 'Marín', 'González', 'eugenioconrado.marin@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Deny', 'Martínez', 'Trejo', 'deny.martinez@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Ana Columba Zurita', 'Martínez', 'Aguilar', 'cmartinez@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('José Elías', 'Martínez', 'Arias', 'elias.martinez@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Edna Militza', 'Martínez', 'Prado', 'ednamilitza.martinez@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Jorge', 'Mendoza', 'Zapata', 'jorge.mendoza@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Roxana Noemí', 'Moreno', 'Real', 'roxana.moreno@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Juan Pablo', 'Murillo', 'Ruiz', 'pmurillo@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Angélica María', 'Ortiz', 'Gaucín', 'angelicamaria.ortiz@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Eduardo José', 'Pérez', 'Pintor', 'eduardo.perez@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Irma De Jesús', 'Ramírez', 'Álvarez', 'irma.ramirez@leon.tecnm.mx', 'Licenciatura', 'NONE'),
('Jesús Enrique', 'Ramírez', 'Méndez', 'enrique.ramirez@leon.tecnm.mx', 'Licenciatura', 'NONE');
